### ISSUE TITLE
Theme selection does not present 

### ISSUE THREAD

**Issue by nehrbash** [mukul29/legacy-theme-auto-switcher-gnome-extension#2] opened 2022-07-14 02:01 UTC
# What
Every time I lock or reboot the selected theme is cleared and I have to open tweaks again to set the theme. 

Not sure if this is an actual issue with your extension or an issue with how extension are cached and loaded.

**Comment by mukul29** [comment] 2022-07-14 05:26
Sorry, I'm unable to reproduce this. Can you try disabling all other extensions and see if this is still happening?

**Comment by mukul29** [comment] 2022-07-27 17:46
Closing this since I'm still unable to reproduce this.

**Closed as completed by mukul29** 2022-07-27 17:46 UTC
